name: Veer Pipeline

on:
  pull_request:
  push:
    branches:
      - main

env:
  WORKSPACE_ROOT:  ${{ github.workspace }}

jobs:
  veer-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: brute force run
        run: |
          export RV_ROOT="$(pwd)"
          echo "Installing dependencies...."
          sudo apt -y install git make help2man perl python3 make autoconf g++ flex bison ccache zlib1g-dev patchutils wget
          sudo apt -y install automake autotools-dev curl libmpc-dev libmpfr-dev libgmp-dev gawk texinfo gperf bc libunwind-dev
          sudo apt -y install libgoogle-perftools-dev numactl perl-doc libfl2 libfl-dev libexpat-dev libtool libjson-perl
          sudo apt -y install build-essential device-tree-compiler
          echo "Installing Verilator....."
          sudo apt -y install verilator
          echo "Getting riscv toolchain....."
          sudo apt isntall gcc-riscv64-unknown-elf
          echo "All dependencies have been installed..."
          echo "Configuring Veer..."
          ${RV_ROOT}/configs/veer.config
          echo "Running Smoke Simulation now...." 
          sudo ${RV_ROOT}/run_smoke
