name: Veer Pipeline

on:
  pull_request:
  push:
    branches:
      - main

env:
  RV_ROOT: ${{ github.workspace }}

jobs:
  veer-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          echo "Installing dependencies...."
          sudo apt -y update
          sudo apt -y install git make help2man perl python3 make autoconf g++ flex bison ccache zlib1g-dev patchutils wget
          sudo apt -y install automake autotools-dev curl libmpc-dev libmpfr-dev libgmp-dev gawk texinfo gperf bc libunwind-dev
          sudo apt -y install libgoogle-perftools-dev numactl perl-doc libfl2 libfl-dev libexpat-dev libtool libjson-perl
          sudo apt -y install build-essential device-tree-compiler
          echo "Installing Verilator....."
          sudo apt -y install verilator
          echo "Getting riscv toolchain....."
          wget https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2024.03.01/riscv64-elf-ubuntu-20.04-gcc-nightly-2024.03.01-nightly.tar.gz
          echo "Extracting toolchain....."
          tar -zxvf ./riscv64-elf-ubuntu-20.04-gcc-nightly-2024.03.01-nightly.tar.gz
          echo "Updating PATH variable...."
          cd ./riscv/bin && echo "RISCV=$(pwd)" >> $GITHUB_ENV
          echo "$RISCV/bin" >> $GITHUB_PATH
          echo "All dependencies have been installed..."

      - name: Configure Veer
        run: echo "Configuring Veer..." && ${{ env.RV_ROOT }}/configs/veer.config

      - name: Run RTL Simulation
        run: 
          echo "Running RTL Simulation now...." && sudo  make -f ${{ env.RV_ROOT}}/tools/Makefile TEST=example_c_test

