name: Veer Pipeline

on:
  pull_request:
  push:
    branches:
      - main

env:
  WORKSPACE_ROOT:  ${{ github.workspace }}

jobs:
  veer-job:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: brute force run
        run: |
          export RV_ROOT="$(pwd)"
          echo "Installing dependencies....
          sudo apt-get install gcc-riscv64-unknown-elf
          sudo apt-get -y install git make help2man perl python3 make autoconf g++ flex bison ccache zlib1g-dev patchutils wget
          sudo apt-get -y install automake autotools-dev curl libmpc-dev libmpfr-dev libgmp-dev gawk texinfo gperf bc libunwind-dev
          sudo apt-get -y install libgoogle-perftools-dev numactl perl-doc libfl2 libfl-dev libexpat-dev libtool libjson-perl
          sudo apt-get -y install build-essential device-tree-compiler
          echo "Installing Verilator....."
          sudo apt-get -y install verilator
          echo "Getting riscv toolchain....."
          wget https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2024.03.01/riscv64-elf-ubuntu-20.04-gcc-nightly-2024.03.01-nightly.tar.gz          
          echo "Extracting toolchain....."
          tar -zxvf ./riscv64-elf-ubuntu-20.04-gcc-nightly-2024.03.01-nightly.tar.gz
          echo "Toolchain extraction done......."
          cd ./riscv/bin && export RISCV="$(pwd)" && sudo cp ./riscv64-unknown-elf-gcc /usr/bin && sudo cp ./riscv64-unknown-elf-cpp /usr/bin && cd ../../
          echo "RISCV binaries are in $RISCV"
          echo "Adding it to the PATH variable...."
          export PATH="${PATH}:${RISCV}"
          echo "Checking..... $PATH"
          echo "All dependencies have been installed..."
          echo "Configuring Veer..."
          ${RV_ROOT}/configs/veer.config
          echo "Running Smoke Simulation now...." 
          sudo ${RV_ROOT}/run_smoke
